// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEqBF_tT5O2CfS7mVqW7K7A1groB-jdHA',
    appId: '1:361712152974:web:b27e782458749d82cdf4df',
    messagingSenderId: '361712152974',
    projectId: 'destify-2ee97',
    authDomain: 'destify-2ee97.firebaseapp.com',
    storageBucket: 'destify-2ee97.firebasestorage.app',
    measurementId: 'G-T6CPJ7F4EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx2tmN2IfZvCVW6gxbvztmOARb8MU4Szs',
    appId: '1:361712152974:android:1c1167fd603e4d16cdf4df',
    messagingSenderId: '361712152974',
    projectId: 'destify-2ee97',
    storageBucket: 'destify-2ee97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk_0f0xrq-PnIr2lvaYykYEttyc7dhaCE',
    appId: '1:361712152974:ios:ce028d5d6c2a5afccdf4df',
    messagingSenderId: '361712152974',
    projectId: 'destify-2ee97',
    storageBucket: 'destify-2ee97.firebasestorage.app',
    iosBundleId: 'com.example.destify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk_0f0xrq-PnIr2lvaYykYEttyc7dhaCE',
    appId: '1:361712152974:ios:ce028d5d6c2a5afccdf4df',
    messagingSenderId: '361712152974',
    projectId: 'destify-2ee97',
    storageBucket: 'destify-2ee97.firebasestorage.app',
    iosBundleId: 'com.example.destify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEqBF_tT5O2CfS7mVqW7K7A1groB-jdHA',
    appId: '1:361712152974:web:a2fac752febcca6ecdf4df',
    messagingSenderId: '361712152974',
    projectId: 'destify-2ee97',
    authDomain: 'destify-2ee97.firebaseapp.com',
    storageBucket: 'destify-2ee97.firebasestorage.app',
    measurementId: 'G-2CGC3JC47C',
  );
}
